### PR TITLE
Use ENV instead of export in dockerfile

### PR DESCRIPTION
**Pull request by johscheuer**
You should use in you Dockerfile ENV instead of "export ...".

### CODE REVIEW

**Comment by arnisoph** [comment]
since the variable is needed for those `RUN`s only, what is the benefit of adding an additional image layer here?

**Comment by arnisoph** [comment]
:)

**Comment by johscheuer** [comment]
After some research I found that it actually is an Antipattern -> https://github.com/docker/docker/issues/4032 but you can find this in many Dockerfiles around the web (what doesn't mean that it has to be good). :)

**Comment by arnisoph** [comment]
thank you for these background details!

**Pull request closed without merging**
